/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;
import javax.swing.JOptionPane;
import modelo.*;

/**
 *
 * @author Mathias Ciancio - CO6607
 */
public class Sistema extends javax.swing.JFrame {
    private static ManteEvento frameManteEvento;
    private static ManteCiudad frameManteCiudad;
    private static MantePonencia frameMantePonencia;
    private static ManteEventoPonencia frameManteEvtPon;
    /**
     * Creates new form Sistema
     */
    public Sistema() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        frameManteEvento = new ManteEvento();
        frameManteCiudad = new ManteCiudad();
        frameMantePonencia = new MantePonencia();
        frameManteEvtPon = new ManteEventoPonencia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        mnubarMenu = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mniSalir = new javax.swing.JMenuItem();
        mnuMantenimiento = new javax.swing.JMenu();
        mnuMEvento = new javax.swing.JMenu();
        mniEACiudad = new javax.swing.JMenuItem();
        mniEAEvento = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mniPAPonencia = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuManteEvtPon = new javax.swing.JMenuItem();
        mnuConsulta = new javax.swing.JMenu();
        mniCEvento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 720));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 699, Short.MAX_VALUE)
        );

        mnuArchivo.setText("Archivo");

        mniSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        mniSalir.setText("Salir");
        mniSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSalirActionPerformed(evt);
            }
        });
        mnuArchivo.add(mniSalir);

        mnubarMenu.add(mnuArchivo);

        mnuMantenimiento.setText("Mantenimiento");

        mnuMEvento.setText("Evento");

        mniEACiudad.setText("Cargar Ciudad");
        mniEACiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEACiudadActionPerformed(evt);
            }
        });
        mnuMEvento.add(mniEACiudad);

        mniEAEvento.setText("Nuevo Evento");
        mniEAEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEAEventoActionPerformed(evt);
            }
        });
        mnuMEvento.add(mniEAEvento);

        mnuMantenimiento.add(mnuMEvento);

        jMenu1.setText("Ponencia");

        mniPAPonencia.setText("Cargar Ponencia");
        mniPAPonencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPAPonenciaActionPerformed(evt);
            }
        });
        jMenu1.add(mniPAPonencia);

        mnuMantenimiento.add(jMenu1);
        mnuMantenimiento.add(jSeparator1);

        mnuManteEvtPon.setText("Asignar Ponencias a Eventos");
        mnuManteEvtPon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManteEvtPonActionPerformed(evt);
            }
        });
        mnuMantenimiento.add(mnuManteEvtPon);

        mnubarMenu.add(mnuMantenimiento);

        mnuConsulta.setText("Consulta");

        mniCEvento.setText("Evento");
        mnuConsulta.add(mniCEvento);

        mnubarMenu.add(mnuConsulta);

        setJMenuBar(mnubarMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    private void mniEAEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEAEventoActionPerformed
        if(!frameManteEvento.isVisible()){
            escritorio.add(frameManteEvento);
            frameManteEvento.setVisible(true);
        }
    }//GEN-LAST:event_mniEAEventoActionPerformed

    private void mniEACiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEACiudadActionPerformed
        if(!frameManteCiudad.isVisible()){
            escritorio.add(frameManteCiudad);
            frameManteCiudad.setVisible(true);
        }
    }//GEN-LAST:event_mniEACiudadActionPerformed

    private void mniSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSalirActionPerformed
        int salir = JOptionPane.showConfirmDialog(null, "¿Desea salir de la aplicacion?", "Confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (salir == 0){
                System.exit(0);
            }
    }//GEN-LAST:event_mniSalirActionPerformed

    private void mniPAPonenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPAPonenciaActionPerformed
        if(!frameMantePonencia.isVisible()){
            escritorio.add(frameMantePonencia);
            frameMantePonencia.setVisible(true);
        }
    }//GEN-LAST:event_mniPAPonenciaActionPerformed

    private void mnuManteEvtPonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManteEvtPonActionPerformed
        if(!frameManteEvtPon.isVisible()){
            escritorio.add(frameManteEvtPon);
            frameManteEvtPon.setVisible(true);
        }
    }//GEN-LAST:event_mnuManteEvtPonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mniCEvento;
    private javax.swing.JMenuItem mniEACiudad;
    private javax.swing.JMenuItem mniEAEvento;
    private javax.swing.JMenuItem mniPAPonencia;
    private javax.swing.JMenuItem mniSalir;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenu mnuConsulta;
    private javax.swing.JMenu mnuMEvento;
    private javax.swing.JMenuItem mnuManteEvtPon;
    private javax.swing.JMenu mnuMantenimiento;
    private javax.swing.JMenuBar mnubarMenu;
    // End of variables declaration//GEN-END:variables
}
